// Generated by scripts/phase-b-source-build.cjs. Edit the builder, then regenerate.
// Disconnected Phase B candidate; no decoded-video/live handoff or master match is proven.
// Recovered source SHA256 (LF): 96b6c9f390d50bfafaee4b6fa8c5875251945c64f879d38accaab66e81850c49
import * as THREE from 'three';

export function createContinuationScene(canvas) {
  if (!canvas || canvas.nodeName !== 'CANVAS' || !canvas.ownerDocument || typeof canvas.getContext !== 'function') {
    throw new TypeError('createContinuationScene requires an HTML canvas');
  }
  let renderer;
  let disposed = false;
  const resources = new Set();
  const own = resource => { resources.add(resource); return resource; };
  const release = resource => { if (resources.delete(resource)) resource.dispose(); };
  const assertActive = () => { if (disposed) throw new Error('Continuation scene has been disposed'); };
  function dispose() {
    if (disposed) return;
    disposed = true;
    try { for (const resource of resources) resource.dispose(); }
    finally {
      resources.clear();
      if (renderer) {
        try { renderer.dispose(); }
        finally { renderer.forceContextLoss(); renderer = undefined; }
      }
    }
  }
  try {




    const width = 1920;
    const height = 1080;
    canvas.width = width;
    canvas.height = height;

    renderer = new THREE.WebGLRenderer({
      canvas,
      antialias: true,
      powerPreference: 'high-performance',
      preserveDrawingBuffer: true
    });
    renderer.setSize(width, height, false);
    renderer.setPixelRatio(1);
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    renderer.toneMapping = THREE.ACESFilmicToneMapping;
    renderer.toneMappingExposure = 1.15;

    const scene = new THREE.Scene();
    scene.background = new THREE.Color('#000000');

    const camera = new THREE.PerspectiveCamera(46, width / height, 0.1, 50);

    // ==========================================
    // LIGHTING & ATMOSPHERE (reference layout; master equivalence unproven)
    // ==========================================
    const ambientLight = new THREE.AmbientLight('#08181c', 1.0);
    scene.add(ambientLight);

    // Strong pale aqua key light from upper right
    const keyLight = new THREE.DirectionalLight('#a6e6ec', 3.8);
    keyLight.position.set(6.0, 7.5, 4.0);
    scene.add(keyLight);

    // Cool rim light from rear-right
    const rimLight = new THREE.DirectionalLight('#68c0cc', 2.5);
    rimLight.position.set(4.0, 2.0, -2.0);
    scene.add(rimLight);

    // Subtle dark fill light from lower left
    const fillLight = new THREE.DirectionalLight('#142a30', 1.0);
    fillLight.position.set(-5.0, -3.0, 2.0);
    scene.add(fillLight);

    // Point light for close particle specular glints
    const glintLight = new THREE.PointLight('#b8f4fa', 3.0, 12, 1.1);
    glintLight.position.set(3.2, 3.2, 1.8);
    scene.add(glintLight);

    // Atmospheric dark water studio backdrop with diagonal light rays
    const bgGeo = own(new THREE.PlaneGeometry(32, 18));
    const bgMat = own(new THREE.ShaderMaterial({
      uniforms: {
        uLightIntensity: { value: 0.0 }
      },
      vertexShader: `
        varying vec2 vUv;
        void main() {
          vUv = uv;
          gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform float uLightIntensity;
        varying vec2 vUv;
        void main() {
          // Dark charcoal and deep gray-green gradient matching 01.png
          vec3 darkCharcoal = vec3(0.008, 0.016, 0.020); // #020405
          vec3 deepGreen    = vec3(0.020, 0.042, 0.048); // #050b0c
          vec3 aquaGlow     = vec3(0.065, 0.145, 0.165);

          // Diagonal light shafts from top right
          float shaftAngle = vUv.x * 0.75 + vUv.y * 0.65;
          float shaft1 = sin(shaftAngle * 42.0) * 0.5 + 0.5;
          float shaft2 = sin((shaftAngle + 0.15) * 78.0) * 0.5 + 0.5;
          float rays = (shaft1 * 0.65 + shaft2 * 0.35) * smoothstep(0.40, 0.95, vUv.x) * smoothstep(0.30, 0.95, vUv.y);

          vec3 base = mix(darkCharcoal, deepGreen, vUv.x * 0.7 + vUv.y * 0.3);
          vec3 col = (base + aquaGlow * rays * 1.3) * uLightIntensity;
          gl_FragColor = vec4(col, 1.0);
        }
      `,
      depthWrite: false
    }));
    const bgMesh = new THREE.Mesh(bgGeo, bgMat);
    bgMesh.position.set(0.6, 0.0, -6.5);
    scene.add(bgMesh);

    // ==========================================
    // PARTICLE GEOMETRIES & MATERIALS
    // ==========================================

    // Material 1: Translucent plastic flakes (crinkled translucent film)
    const fragmentMat = own(new THREE.MeshPhysicalMaterial({
      color: new THREE.Color('#d4e8eb'),
      transmission: 0.68,
      opacity: 0.95,
      transparent: true,
      roughness: 0.22,
      ior: 1.50,
      thickness: 0.04,
      specularIntensity: 1.2,
      specularColor: new THREE.Color('#d8f2f5'),
      side: THREE.DoubleSide
    }));

    const blueFragmentMat = own(new THREE.MeshPhysicalMaterial({
      color: new THREE.Color('#8ab9bc'),
      transmission: 0.64,
      opacity: 0.92,
      transparent: true,
      roughness: 0.25,
      ior: 1.48,
      thickness: 0.05,
      specularIntensity: 1.1,
      side: THREE.DoubleSide
    }));

    // Fixed seeded weathering for the disconnected offline candidate.
    const textureCanvas = canvas.ownerDocument.createElement('canvas');
    textureCanvas.width = textureCanvas.height = 256;
    const context = textureCanvas.getContext('2d');
    if (!context) throw new Error('A 2D canvas context is required for the weathering texture');
    const pixels = context.createImageData(256,256);
    let seed = 17329;
    for(let y=0;y<256;y++) for(let x=0;x<256;x++) {
      seed = (Math.imul(seed,1664525)+1013904223)>>>0;
      const noise = seed/4294967296;
      const vein = Math.pow(Math.abs(Math.sin(x*0.071 + Math.sin(y*0.063)*2.1)),18);
      const value = Math.min(255,145 + noise*65 + vein*45);
      const index = (y*256+x)*4;
      pixels.data[index]=value;pixels.data[index+1]=value;pixels.data[index+2]=value;pixels.data[index+3]=255;
    }
    context.putImageData(pixels,0,0);
    const weathering = own(new THREE.CanvasTexture(textureCanvas));
    // Intentional linear modulation for the shared color/bump map, not calibrated albedo.
    weathering.colorSpace = THREE.NoColorSpace;
    weathering.wrapS = weathering.wrapT = THREE.RepeatWrapping;
    for(const material of [fragmentMat,blueFragmentMat]) {
      material.map = weathering; material.bumpMap = weathering; material.bumpScale = 0.026;
      material.roughness = 0.36;
    }

    // Material 2: Thin synthetic fibers with subtle internal glow
    const fiberMat = own(new THREE.MeshStandardMaterial({
      color: new THREE.Color('#98d8e8'),
      emissive: new THREE.Color('#1e4c5a'),
      emissiveIntensity: 0.4,
      roughness: 0.3,
      metalness: 0.1
    }));

    const blueFiberMat = own(new THREE.MeshStandardMaterial({
      color: new THREE.Color('#4888b4'),
      emissive: new THREE.Color('#143548'),
      emissiveIntensity: 0.45,
      roughness: 0.28,
      metalness: 0.15
    }));

    // Material 3: Solid polymer granules
    const granuleMat = own(new THREE.MeshStandardMaterial({
      color: new THREE.Color('#e2eeee'),
      roughness: 0.38,
      metalness: 0.06,
      flatShading: true
    }));

    const amberGranuleMat = own(new THREE.MeshStandardMaterial({
      color: new THREE.Color('#c8a882'),
      roughness: 0.44,
      metalness: 0.08,
      flatShading: true
    }));

    // Edge highlight material for fragments (delicate bright rim)
    const edgeMat = own(new THREE.LineBasicMaterial({
      color: new THREE.Color('#bbf0f5'),
      transparent: true,
      opacity: 0.38,
      linewidth: 1
    }));

    // Helper: Create wrinkled translucent flake
    function createWrinkledFlake(radii, angles, scale = 1.0) {
      const group = new THREE.Group();
      
      // Create 2D shape
      const shape = new THREE.Shape();
      for (let i = 0; i < angles.length; i++) {
        const a = angles[i];
        const r = radii[i] * scale;
        const x = Math.cos(a) * r;
        const y = Math.sin(a) * r;
        if (i === 0) shape.moveTo(x, y);
        else shape.lineTo(x, y);
      }
      shape.closePath();

      // Shape geometry with subdivision
      const flat = own(new THREE.ShapeGeometry(shape, 12));
      const raw = flat.index ? own(flat.toNonIndexed()) : flat;
      const source = raw.getAttribute('position');
      const vertices = [], uv = [];
      const a = new THREE.Vector3(), b = new THREE.Vector3(), c = new THREE.Vector3();
      const divisions = 10;
      const point = (i,j) => a.clone().multiplyScalar(1-(i+j)/divisions)
        .addScaledVector(b,i/divisions).addScaledVector(c,j/divisions);
      const add = p => {vertices.push(p.x,p.y,p.z);uv.push(p.x+0.5,p.y+0.5);};
      for (let triangle=0; triangle<source.count; triangle+=3) {
        a.fromBufferAttribute(source,triangle); b.fromBufferAttribute(source,triangle+1); c.fromBufferAttribute(source,triangle+2);
        for(let i=0;i<divisions;i++) for(let j=0;j<divisions-i;j++) {
          add(point(i,j));add(point(i+1,j));add(point(i,j+1));
          if(i+j<divisions-1) {add(point(i+1,j));add(point(i+1,j+1));add(point(i,j+1));}
        }
      }
      const geom = own(new THREE.BufferGeometry());
      geom.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));
      geom.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));
      release(raw); if(raw !== flat) release(flat);
      const pos = geom.attributes.position;
      
      // Wrinkle displacement
      for (let i = 0; i < pos.count; i++) {
        const px = pos.getX(i);
        const py = pos.getY(i);
        const pz = 0.035 * Math.sin(px * 18.0 + 1.2) * Math.cos(py * 16.0 + 0.8)
                 + 0.015 * Math.sin(px * 35.0) * Math.sin(py * 32.0);
        pos.setZ(i, pz);
      }
      geom.computeVertexNormals();

      const mesh = new THREE.Mesh(geom, fragmentMat);
      group.add(mesh);

      // Add edge line highlight
      const edges = own(new THREE.EdgesGeometry(geom, 42));
      const line = new THREE.LineSegments(edges, edgeMat);
      group.add(line);

      return { group, mesh, line };
    }

    // Helper: Create deformed granule
    function createGranuleMesh(radius, mat) {
      const geom = own(new THREE.IcosahedronGeometry(radius, 2));
      const pos = geom.attributes.position;
      for (let i = 0; i < pos.count; i++) {
        let x = pos.getX(i);
        let y = pos.getY(i);
        let z = pos.getZ(i);
        const noise = 1.0 + 0.22 * Math.sin(x * 24.0) * Math.cos(y * 22.0) * Math.sin(z * 18.0);
        pos.setXYZ(i, x * noise, y * noise, z * noise);
      }
      geom.computeVertexNormals();
      return new THREE.Mesh(geom, mat);
    }

    // Helper: Create fiber tube
    function createFiberMesh(points, radius, mat) {
      const curve = new THREE.CatmullRomCurve3(points);
      const geom = own(new THREE.TubeGeometry(curve, 40, radius, 8, false));
      return new THREE.Mesh(geom, mat);
    }

    // ==========================================
    // PARTICLE SCENE ASSEMBLY (reference layout; master equivalence unproven)
    // ==========================================
    const particles = [];

    function registerParticle(obj, targetPos, driftDir, driftDist, rotSpeed) {
      scene.add(obj);
      particles.push({
        obj,
        targetPos: targetPos.clone(),
        driftDir: driftDir.clone().normalize(),
        driftDist,
        baseRot: obj.rotation.clone(),
        rotSpeed
      });
    }

    // --- FRAGMENTS ---
    // Fragment 1: Large faceted translucent shard (upper-right: screenspace ~0.81, 0.31)
    {
      const radii = [0.45, 0.30, 0.48, 0.25, 0.40, 0.24, 0.36];
      const angles = [0.0, 0.9, 1.8, 2.7, 3.6, 4.5, 5.4];
      const { group } = createWrinkledFlake(radii, angles, 1.05);
      group.rotation.set(0.25, -0.35, 0.40);
      const targetPos = new THREE.Vector3(2.15, 1.05, -0.2);
      registerParticle(group, targetPos, new THREE.Vector3(0.6, 0.4, 0.2), 0.16, new THREE.Vector3(0.04, 0.08, -0.06));
    }

    // Fragment 2: Blue-tinted translucent shard (mid-right: screenspace ~0.80, 0.53)
    {
      const radii = [0.32, 0.20, 0.38, 0.18, 0.30, 0.22];
      const angles = [0.2, 1.2, 2.3, 3.4, 4.4, 5.6];
      const { group, mesh } = createWrinkledFlake(radii, angles, 0.95);
      mesh.material = blueFragmentMat;
      group.rotation.set(-0.18, 0.30, -0.45);
      const targetPos = new THREE.Vector3(2.05, -0.15, -0.35);
      registerParticle(group, targetPos, new THREE.Vector3(0.7, -0.2, 0.15), 0.14, new THREE.Vector3(-0.06, 0.05, 0.04));
    }

    // Fragment 3: Lower right triangular shard (screenspace ~0.74, 0.68)
    {
      const radii = [0.36, 0.26, 0.40, 0.20, 0.34];
      const angles = [0.1, 1.3, 2.6, 3.9, 5.2];
      const { group } = createWrinkledFlake(radii, angles, 1.0);
      group.rotation.set(0.32, -0.15, 0.25);
      const targetPos = new THREE.Vector3(1.72, -0.85, 0.1);
      registerParticle(group, targetPos, new THREE.Vector3(0.5, -0.5, 0.25), 0.18, new THREE.Vector3(0.05, -0.04, 0.07));
    }

    // Fragment 4: Mid-left shard (screenspace ~0.59, 0.43)
    {
      const radii = [0.26, 0.16, 0.30, 0.14, 0.24];
      const angles = [0.3, 1.5, 2.9, 4.1, 5.4];
      const { group } = createWrinkledFlake(radii, angles, 0.9);
      group.rotation.set(0.12, 0.38, -0.28);
      const targetPos = new THREE.Vector3(0.75, 0.30, -0.4);
      registerParticle(group, targetPos, new THREE.Vector3(-0.3, 0.3, 0.1), 0.12, new THREE.Vector3(0.03, 0.06, -0.04));
    }

    // Fragment 5: Defocused distant background shard (~0.53, 0.15)
    {
      const radii = [0.22, 0.15, 0.26, 0.12, 0.20];
      const angles = [0.1, 1.4, 2.8, 4.0, 5.2];
      const { group } = createWrinkledFlake(radii, angles, 0.85);
      group.rotation.set(0.4, 0.1, 0.6);
      const targetPos = new THREE.Vector3(0.38, 1.48, -1.8);
      registerParticle(group, targetPos, new THREE.Vector3(-0.2, 0.5, 0.05), 0.08, new THREE.Vector3(0.02, 0.03, 0.02));
    }

    // Fragment 6: Distant lower-right flake (~0.82, 0.90)
    {
      const radii = [0.28, 0.18, 0.32, 0.16, 0.25];
      const angles = [0.0, 1.2, 2.5, 3.8, 5.0];
      const { group } = createWrinkledFlake(radii, angles, 0.9);
      group.rotation.set(-0.2, 0.4, 0.1);
      const targetPos = new THREE.Vector3(2.18, -1.68, -1.4);
      registerParticle(group, targetPos, new THREE.Vector3(0.4, -0.6, 0.1), 0.09, new THREE.Vector3(-0.03, 0.04, 0.03));
    }

    // --- FIBERS ---
    // Fiber 1: Upper blue curved strand (screenspace ~0.62, 0.20 to ~0.65, 0.35)
    {
      const pts = [
        new THREE.Vector3(0.82, 1.65, 0.1),
        new THREE.Vector3(0.88, 1.50, 0.05),
        new THREE.Vector3(1.15, 1.34, -0.1),
        new THREE.Vector3(1.26, 1.06, -0.15),
        new THREE.Vector3(1.42, 0.72, -0.2)
      ];
      const mesh = createFiberMesh(pts, 0.013, blueFiberMat);
      registerParticle(mesh, new THREE.Vector3(0, 0, 0), new THREE.Vector3(0.3, 0.6, 0.2), 0.15, new THREE.Vector3(0.02, 0.05, -0.03));
    }

    // Fiber 2: Long middle-left strand (screenspace ~0.54, 0.55 to ~0.61, 0.85)
    {
      const pts = [
        new THREE.Vector3(0.45, 0.15, 0.25),
        new THREE.Vector3(0.60, -0.22, 0.18),
        new THREE.Vector3(0.76, -0.68, 0.05),
        new THREE.Vector3(0.95, -1.12, -0.1)
      ];
      const mesh = createFiberMesh(pts, 0.011, fiberMat);
      registerParticle(mesh, new THREE.Vector3(0, 0, 0), new THREE.Vector3(-0.3, -0.4, 0.15), 0.14, new THREE.Vector3(0.01, -0.04, 0.02));
    }

    // Fiber 3: Lower blue strand (screenspace ~0.61, 0.82)
    {
      const pts = [
        new THREE.Vector3(0.98, -0.86, 0.3),
        new THREE.Vector3(0.94, -1.16, 0.2),
        new THREE.Vector3(0.92, -1.42, 0.1)
      ];
      const mesh = createFiberMesh(pts, 0.012, blueFiberMat);
      registerParticle(mesh, new THREE.Vector3(0, 0, 0), new THREE.Vector3(0.1, -0.5, 0.2), 0.16, new THREE.Vector3(-0.02, 0.03, -0.02));
    }

    // Fiber 4: Far-right thin strand (screenspace ~0.88, 0.25 to 0.45)
    {
      const pts = [
        new THREE.Vector3(2.58, 1.42, -0.5),
        new THREE.Vector3(2.52, 0.96, -0.6),
        new THREE.Vector3(2.44, 0.52, -0.7)
      ];
      const mesh = createFiberMesh(pts, 0.009, fiberMat);
      registerParticle(mesh, new THREE.Vector3(0, 0, 0), new THREE.Vector3(0.5, 0.3, 0.1), 0.10, new THREE.Vector3(0.01, 0.02, 0.01));
    }

    // Fiber 5: Far-right blue curve (screenspace ~0.91, 0.55 to 0.75)
    {
      const pts = [
        new THREE.Vector3(2.68, 0.10, -0.4),
        new THREE.Vector3(2.72, -0.30, -0.45),
        new THREE.Vector3(2.74, -0.72, -0.5)
      ];
      const mesh = createFiberMesh(pts, 0.010, blueFiberMat);
      registerParticle(mesh, new THREE.Vector3(0, 0, 0), new THREE.Vector3(0.6, -0.2, 0.1), 0.11, new THREE.Vector3(-0.01, 0.02, -0.01));
    }

    // --- GRANULES ---
    // Granule 1: Central polymer bead (screenspace ~0.68, 0.58)
    {
      const mesh = createGranuleMesh(0.082, granuleMat);
      const targetPos = new THREE.Vector3(1.24, -0.30, 0.2);
      registerParticle(mesh, targetPos, new THREE.Vector3(0.2, -0.3, 0.2), 0.16, new THREE.Vector3(0.06, 0.08, 0.05));
    }

    // Granule 2: Small textured bead (screenspace ~0.62, 0.35)
    {
      const mesh = createGranuleMesh(0.065, amberGranuleMat);
      const targetPos = new THREE.Vector3(0.88, 0.60, -0.15);
      registerParticle(mesh, targetPos, new THREE.Vector3(0.1, 0.4, 0.1), 0.13, new THREE.Vector3(-0.05, 0.04, 0.06));
    }

    // Granule 3: Textured bead cluster (screenspace ~0.72, 0.42)
    {
      const mesh = createGranuleMesh(0.072, amberGranuleMat);
      const targetPos = new THREE.Vector3(1.48, 0.34, -0.05);
      registerParticle(mesh, targetPos, new THREE.Vector3(0.4, 0.3, 0.15), 0.14, new THREE.Vector3(0.04, -0.05, 0.04));
    }

    // Granule 4: Amber polymer bead upper right (~0.85, 0.15)
    {
      const mesh = createGranuleMesh(0.060, amberGranuleMat);
      const targetPos = new THREE.Vector3(2.35, 1.50, -0.6);
      registerParticle(mesh, targetPos, new THREE.Vector3(0.5, 0.5, 0.1), 0.10, new THREE.Vector3(0.03, 0.05, -0.03));
    }

    // Granule 5: Lower cluster bead (~0.85, 0.73)
    {
      const mesh = createGranuleMesh(0.075, amberGranuleMat);
      const targetPos = new THREE.Vector3(2.30, -0.96, -0.35);
      registerParticle(mesh, targetPos, new THREE.Vector3(0.5, -0.4, 0.15), 0.12, new THREE.Vector3(-0.04, 0.05, 0.05));
    }

    // Granule 6: Soft bead lower center (~0.68, 0.82)
    {
      const mesh = createGranuleMesh(0.088, granuleMat);
      const targetPos = new THREE.Vector3(1.35, -1.42, -0.6);
      registerParticle(mesh, targetPos, new THREE.Vector3(0.2, -0.6, 0.1), 0.11, new THREE.Vector3(0.03, -0.03, 0.04));
    }

    // Motes for depth (controlled by lighting)
    const moteMat = own(new THREE.MeshStandardMaterial({
      color: new THREE.Color('#94d0d8'),
      roughness: 0.5,
      metalness: 0.1
    }));
    const moteGeo = own(new THREE.SphereGeometry(0.016, 6, 6));
    const motes = [];
    const moteCoords = [
      [1.15, 0.82, -1.2], [1.82, 0.42, -0.8], [0.92, -0.48, -0.9],
      [2.42, -0.18, -1.5], [1.62, -1.18, -1.1], [2.12, 1.22, -1.8],
      [0.62, 1.12, -1.4], [1.42, -0.08, -1.0], [2.72, 0.72, -1.2]
    ];
    for (const c of moteCoords) {
      const m = new THREE.Mesh(moteGeo, moteMat);
      m.position.set(c[0], c[1], c[2]);
      scene.add(m);
      motes.push({ mesh: m, basePos: new THREE.Vector3(c[0], c[1], c[2]) });
    }

    // ==========================================
    // TRAJECTORY & TIME FUNCTION
    // 4.0 SECONDS = 120 FRAMES (0 to 119)
    // ==========================================

    const camStart = new THREE.Vector3(0.10, -0.06, 5.25);
    const camEnd   = new THREE.Vector3(0.22, 0.02, 4.30);

    const targetStart = new THREE.Vector3(0.55, -0.05, 0.0);
    const targetEnd   = new THREE.Vector3(0.75, 0.02, 0.0);

    function renderAtSeconds(seconds) {
      const t = Math.max(0, seconds);
      const liveTime = Math.max(0, t - 4);
      const interactionMix = Math.min(1, liveTime / 0.5);
      const scatterMix = scatterAt === null ? 0 : Math.sin(Math.min(Math.PI, Math.max(0, t - scatterAt) * 0.8)) * 0.09;

      // 1. LIGHTING & EMERGENCE (Strict Prompt 06 & 07 timing)
      // 0.00s - 0.15s: EXACT FULL-FRAME OPTICAL BLACK (matching microscope-exit-frame.png)
      // 0.15s - 1.20s: Smooth whole-frame emergence into dark water
      // 1.20s - 4.00s: Full illumination (1.0)
      let lightIntensity = 0.0;
      if (t <= 0.15) {
        lightIntensity = 0.0;
      } else if (t < 1.20) {
        const u = (t - 0.15) / 1.05;
        lightIntensity = u * u * (3.0 - 2.0 * u);
      } else {
        lightIntensity = 1.0;
      }

      // Exact zero check for full optical black
      if (lightIntensity === 0.0) {
        scene.visible = false;
        renderer.setClearColor(0x000000, 1.0);
        renderer.clear();
        return;
      }
      scene.visible = true;

      ambientLight.intensity = 1.0 * lightIntensity;
      keyLight.intensity = 3.8 * lightIntensity;
      rimLight.intensity = 2.5 * lightIntensity;
      fillLight.intensity = 1.0 * lightIntensity;
      glintLight.intensity = 3.0 * lightIntensity;
      bgMat.uniforms.uLightIntensity.value = lightIntensity;

      fiberMat.emissiveIntensity = 0.4 * lightIntensity;
      blueFiberMat.emissiveIntensity = 0.45 * lightIntensity;
      edgeMat.opacity = 0.38 * lightIntensity;

      // 2. CAMERA FORWARD GLIDE & DECELERATION
      let camProgress = 0.0;
      if (t <= 3.20) {
        const u = t / 3.20;
        camProgress = 1.0 - Math.pow(1.0 - u, 3.0);
      } else {
        camProgress = 1.0;
      }

      const microDriftX = Math.sin(t * 0.8) * 0.003;
      const microDriftY = Math.cos(t * 0.9) * 0.002;

      camera.position.lerpVectors(camStart, camEnd, camProgress);
      camera.position.x += microDriftX;
      camera.position.y += microDriftY;

      const currentTarget = new THREE.Vector3().lerpVectors(targetStart, targetEnd, camProgress);
      camera.lookAt(currentTarget);
      camera.updateMatrixWorld(true);

      // 3. PARTICLE OUTWARD IMPULSE & SETTLING
      let impulse = 0.0;
      if (t >= 1.20 && t <= 2.80) {
        const u = (t - 1.20) / 1.60;
        impulse = Math.sin(Math.PI * u);
      }

      for (const p of particles) {
        const offset = p.driftDir.clone().multiplyScalar(p.driftDist * impulse);
        const forwardOffset = (1.0 - camProgress) * p.driftDist * 0.4;
        
        const pDriftX = Math.sin(t * 0.7 + p.targetPos.x) * 0.004;
        const pDriftY = Math.cos(t * 0.6 + p.targetPos.y) * 0.003;

        p.obj.position.copy(p.targetPos)
          .add(offset)
          .add(p.driftDir.clone().multiplyScalar(forwardOffset));
        p.obj.position.x += pDriftX;
        p.obj.position.y += pDriftY;
        if (liveTime > 0) {
          p.obj.position.addScaledVector(p.driftDir, scatterMix);
          if (pointer) {
            const screen = p.obj.position.clone().project(camera);
            const dx = screen.x - pointer.x, dy = screen.y - pointer.y;
            const distance = Math.hypot(dx,dy);
            const weight = Math.max(0, 1 - distance / 0.7) * 0.018 * interactionMix;
            p.obj.position.x += dx * weight; p.obj.position.y += dy * weight;
          }
        }

        p.obj.rotation.x = p.baseRot.x + p.rotSpeed.x * t * 0.4;
        p.obj.rotation.y = p.baseRot.y + p.rotSpeed.y * t * 0.4;
        p.obj.rotation.z = p.baseRot.z + p.rotSpeed.z * t * 0.4;
      }

      for (let i = 0; i < motes.length; i++) {
        const m = motes[i];
        m.mesh.position.x = m.basePos.x + Math.sin(t * 0.5 + i) * 0.008;
        m.mesh.position.y = m.basePos.y + Math.cos(t * 0.4 + i) * 0.006;
      }

      renderer.render(scene, camera);
    };

    let scatterAt = null;
    let pointer = null;
    let lastTime = 4;
    const baseRender = renderAtSeconds;
    return {
      renderAtSeconds(t) {
        assertActive();
        if (!Number.isFinite(t) || t < 0) throw new RangeError('Scene time must be finite and nonnegative');
        lastTime = t;
        baseRender(t);
      },
      // Fixed source raster; this is not a responsive or approved handoff renderer.
      resize() { assertActive(); renderer.setSize(width, height, false); },
      setPointer(x, y) {
        assertActive();
        if (x === null) { pointer = null; return; }
        if (!Number.isFinite(x) || !Number.isFinite(y) || Math.abs(x) > 1 || Math.abs(y) > 1) {
          throw new RangeError('Pointer must contain two finite normalized coordinates in [-1, 1]');
        }
        pointer = {x, y};
      },
      scatter() { assertActive(); scatterAt = lastTime; },
      dispose
    };
  } catch (error) {
    dispose();
    throw error;
  }
}
