const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
  const url = process.env.QA_URL || 'http://localhost:3017/';
  const browser = await chromium.launch({channel:'chrome',headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    await page.addInitScript(()=>sessionStorage.setItem('ripple-entered','1'));
    await page.goto(url);
    const dot = page.locator('[data-fluid-cursor]');
    await dot.waitFor({state:'attached'});
    assert.equal(await dot.evaluate(e=>getComputedStyle(e).display),'none');
    // Existing non-interactive narrative heading provides a known mouse target.
    const heading = page.locator('#countermeasure-title');
    await heading.scrollIntoViewIfNeeded();
    await page.waitForTimeout(500);
    const box = await heading.boundingBox();
    const x=box.x+30, y=box.y+20;
    await page.mouse.move(x,y);
    await page.waitForTimeout(100);
    await page.mouse.move(x+100,y);
    const early = await dot.evaluate(e=>parseFloat(e.style.getPropertyValue('--fluid-x')));
    assert.ok(early < x+99,'Cursor must lag a moving pointer');
    await page.waitForTimeout(700);
    const r = await dot.boundingBox();
    assert.ok(Math.abs(r.x+r.width/2-(x+100))<1,'Rendered cursor must settle in CSS pixels');
    console.log('PASS: hidden initially, inertia and rendered pixel position');
    const link = page.locator('.countermeasure-action');
    await link.scrollIntoViewIfNeeded();
    await page.waitForTimeout(300);
    const b = await link.boundingBox();
    const px=b.x+20, py=b.y+b.height/2;
    await page.mouse.move(px,py);
    await page.waitForTimeout(700);
    assert.equal(await dot.getAttribute('data-state'),'link');
    const pulled = await dot.boundingBox();
    assert.ok(pulled.x+pulled.width/2>px+5 && pulled.x+pulled.width/2<=px+25,'Bounded attraction toward hovered link');
    assert.equal(await dot.evaluate(e=>getComputedStyle(e).pointerEvents),'none');
    assert.notEqual(await link.evaluate(e=>getComputedStyle(e).cursor),'none');
    const settledStyle=await dot.getAttribute('style');
    await page.waitForTimeout(250);
    assert.equal(await dot.getAttribute('style'),settledStyle);
    console.log('PASS: magnetic link reaction, native cursor preserved, settles');
    await page.screenshot({path:'C:/Users/ayada/AppData/Local/Temp/fluid-cursor-desktop.png'});
    await page.keyboard.press('Tab');
    assert.equal(await dot.getAttribute('data-visible'),'false');
    await link.focus();
    await page.keyboard.press('Enter');
    await page.waitForURL('**/#submit');
    await page.locator('form').waitFor();
    const input=page.locator('input[type="email"]').first();
    await input.hover();
    assert.equal(await dot.getAttribute('data-visible'),'false','Do not obscure fields');
    console.log('PASS: keyboard navigation and form exclusion');
    await page.emulateMedia({reducedMotion:'reduce'});
    await dot.waitFor({state:'detached'});
    await page.emulateMedia({reducedMotion:'no-preference'});
    await dot.waitFor({state:'attached'});
    assert.equal(await dot.getAttribute('data-visible'),'false');
    console.log('PASS: live reduced-motion changes unmount/remount hidden');
    const touch=await browser.newContext({viewport:{width:375,height:700},hasTouch:true,isMobile:true});
    const mobile=await touch.newPage();
    await mobile.goto(url);
    await mobile.waitForTimeout(500);
    assert.equal(await mobile.locator('[data-fluid-cursor]').count(),0);
    await touch.close();
    console.log('PASS: touch does not mount cursor');
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
