const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({channel:'chrome', headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    await page.addInitScript(() => sessionStorage.setItem('ripple-entered','1'));
    await page.goto(process.env.QA_URL || 'http://localhost:3015', {waitUntil:'domcontentloaded'});
    const stage = page.locator('.specimen-stage');
    const canvas = stage.locator('canvas');
    await stage.scrollIntoViewIfNeeded();
    await page.waitForFunction(() => document.querySelector('.specimen-stage canvas')?.dataset.rendered === 'macro');
    const before = await canvas.evaluate(c => c.toDataURL());
    const readout = await stage.locator('.specimen-readout').innerText();
    await stage.getByRole('button',{name:'UV view',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('.specimen-stage canvas')?.dataset.rendered === 'uv');
    assert.notEqual(await canvas.evaluate(c => c.toDataURL()), before, 'UV must change canvas pixels');
    assert.notEqual(await stage.locator('.specimen-readout').innerText(), readout, 'UV must change readout');
    assert.equal(await stage.getByRole('button',{name:'UV view',exact:true}).getAttribute('aria-pressed'),'true');
    assert.match(await stage.locator('.specimen-readout').innerText(), /240,000/);
    console.log('PASS: actual UV click changes canvas pixels, readout and pressed state');
    const uv = await canvas.evaluate(c=>c.toDataURL());
    await stage.getByRole('slider',{name:'Rotate specimen'}).focus();
    await page.keyboard.press('ArrowRight');
    await page.waitForFunction(() => document.querySelector('.specimen-stage canvas')?.dataset.angle === '5');
    assert.notEqual(await canvas.evaluate(c=>c.toDataURL()),uv);
    console.log('PASS: keyboard rotation changes rendered pixels');
    await stage.scrollIntoViewIfNeeded();
    await stage.screenshot({path:'C:/Users/ayada/AppData/Local/Temp/specimen-uv-desktop.png'});
    await page.setViewportSize({width:375,height:700});
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.waitForTimeout(250);
    assert.equal(await stage.evaluate(s=>[s,...s.querySelectorAll('h2,p,button,canvas,input')].every(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=document.documentElement.clientWidth+1})),true,'Mobile content fits');
    const still = await canvas.evaluate(c=>c.toDataURL());
    await page.waitForTimeout(250);
    assert.equal(await canvas.evaluate(c=>c.toDataURL()),still,'Reduced motion canvas remains static without input');
    console.log('PASS: mobile content fits; reduced-motion canvas stays static');
    await stage.screenshot({path:'C:/Users/ayada/AppData/Local/Temp/specimen-uv-mobile.png'});
    await stage.getByRole('button',{name:'Macro view',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('.specimen-stage canvas')?.dataset.rendered === 'macro');
    console.log('PASS: Macro restored');
    assert.equal(await page.locator('.siphon-stop').count(), 4);
    assert.equal(await page.locator('.countermeasure-stage').count(), 1);
    await page.locator('.countermeasure-action').click();
    await page.waitForSelector('form');
    assert.equal(new URL(page.url()).hash, '#submit');
    assert.equal(await page.locator('.specimen-stage').count(), 0);
    console.log('PASS: four narrative waypoints retained; CTA navigation unmounts inspector');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1});
